name: create-redocly

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:

jobs:

  test_job:
    runs-on: ubuntu-latest
    name: Testing public name
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # use the public name of the action
      - name: redoc-cli test
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: 'bundle utm.yaml -o petstore.html'

      - name: check result
        run: |
          ls -al
          test -f petstore.html || (echo "Missing petstore.html from previous step." && exit 1)

  generate_html:
    runs-on: ubuntu-latest
    name: Generate static HTML
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # use the public name of the action
      - name: redoc-cli
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: 'bundle utm.yaml -o petstore.html'

      - name: check result
        run: |
          ls -al
          test -f petstore.html || (echo "Missing petstore.html from previous step." && exit 1)
